### ISSUE TITLE
mesecons_materials + basic_materials - Silicon lump recipe not shown

### ISSUE THREAD

**Issue by bell07** [minetest-mods/craftguide#91]
As reported in https://forum.minetest.net/viewtopic.php?f=15&p=358409#p358409, the recipe for Silicon lump is not shown in craftguide, but is crafteable. I looked into the code and it seems to be an issue with minetest.register_alias_force()

Homedecor basic_materials:
```
minetest.register_craftitem("basic_materials:silicon", {
        description = "Silicon lump",
        inventory_image = "basic_materials_silicon.png",
})

minetest.register_craft( {
        output = "mesecons_materials:silicon 4",
        recipe = {
                { "default:sand", "default:sand" },
                { "default:sand", "default:steel_ingot" },
        },
})

minetest.register_alias_force("mesecons_materials:silicon", "basic_materials:silicon")
```

Mesecons mesecons_materials:
```
minetest.register_craftitem("mesecons_materials:silicon", {
        image = "mesecons_silicon.png",
        on_place_on_ground = minetest.craftitem_place_item,
        description="Silicon",
})
```

Looks wrong defined in homedecor, but should be still be shown in craftguide

**Comment by kilbith** [comment]
Are these two recipes?

![screenshot_20190930_111123](https://user-images.githubusercontent.com/7883281/65865023-17b51b80-e373-11e9-8bec-2c7550b682a8.png)

**Comment by kilbith** [comment]
Fixed by https://github.com/minetest-mods/craftguide/commit/bb6b3a4ee58cfc1383847e7d74e460e0dfd3ef93

**Comment by bell07** [comment]
The discussion was moved to https://github.com/minetest-mods/craftguide/issues/92, but basically this one is still open. Can you pls. reopen this #91?

The expected behaviour is the "basic_materials:silicon" and "mesecons_materials:silicon" are shown merged in craftguide because of minetest.register_alias_force(). Currently they are 2x items in craftguide, one with recipe how to craft and the other with item usages.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/b09870a5b295f1b87036c0bdb85769600688feb1

**Comment by bell07** [comment]
Still does not work. The 3x Sand + 1x Iron Lump is again not in the list

**Comment by bell07** [comment]
The silicon lump needs to be in usages of sand...

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/937f5f0918fc4c0f3c74274b076828535ceedfa6

**Comment by bell07** [comment]
Found solution that works for me. The issue is in handle_aliases at: 
[local recipes = recipes_cache[oldname]](https://github.com/minetest-mods/craftguide/blob/master/init.lua#L1281)

In my setup the `core.get_all_craft_recipes('basic_materials:silicon')` returned empty table (registered_item), but `core.get_all_craft_recipes('mesecons_materials:silicon')` returns the recipe (oldname).

Added `recipes_cache[oldname] = recipes_cache[oldname] or get_all_recipes(oldname)` before the line, and the recipe is visible now ;-)

**Comment by bell07** [comment]
It does not work again after last changes :-( And I do not see the reason...
Please re-test it with both mods (mesecons_materials + basic_materials) enabled. 

- Silicon lump recipe should be shown once (ok)
- Click to the lump should switch to the Lump usages (does not work)
- Search for sand and then look into sand usages: Lump should be found (does not work)

**Comment by kilbith** [comment]
Nothing has changed in this part. Please conduct your investigation yourself and provide a patch.
